version: '3.8'

services:
  # Main backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 4runr-lead-system
    volumes:
      # Mount the .env file for configuration
      - ./.env:/app/.env:ro
      # Mount logs directory for persistent logs
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/cli/healthCheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - 4runr-network

  # Cron service for scheduled tasks
  cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 4runr-lead-system-cron
    volumes:
      # Mount the .env file for configuration
      - ./.env:/app/.env:ro
      # Mount logs directory for persistent logs
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    entrypoint: ["crond", "-f", "-d", "8"]
    depends_on:
      - backend
    networks:
      - 4runr-network

networks:
  4runr-network:
    driver: bridge