#!/usr/bin/env python3
"""
Send the generated Trivago message to demonstrate the complete workflow.
"""

import sys
import requests
from pathlib import Path

# Add the project root to Python path
sys.path.insert(0, str(Path(__file__).parent))

def send_trivago_message():
    """Send the Trivago message to kyanberg@outlook.com for demonstration."""
    print("📧 Sending Trivago Analysis Message")
    print("=" * 50)
    
    try:
        # Load configuration
        sys.path.append('4runr-outreach-system')
        from shared.config import config
        
        # Get Microsoft Graph configuration
        graph_config = {
            'client_id': config.get('MS_GRAPH_CLIENT_ID'),
            'client_secret': config.get('MS_GRAPH_CLIENT_SECRET'),
            'tenant_id': config.get('MS_GRAPH_TENANT_ID'),
            'sender_email': config.get('MS_GRAPH_SENDER_EMAIL')
        }
        
        print(f"✅ Using Microsoft Graph API")
        print(f"✅ From: {graph_config['sender_email']}")
        print(f"✅ To: kyanberg@outlook.com")
        
        # Get access token
        print(f"\n🔑 Getting access token...")
        url = f"https://login.microsoftonline.com/{graph_config['tenant_id']}/oauth2/v2.0/token"
        
        data = {
            'client_id': graph_config['client_id'],
            'client_secret': graph_config['client_secret'],
            'scope': 'https://graph.microsoft.com/.default',
            'grant_type': 'client_credentials'
        }
        
        response = requests.post(url, data=data)
        
        if response.status_code != 200:
            print(f"❌ Failed to get access token: {response.text}")
            return False
        
        access_token = response.json()['access_token']
        print("✅ Access token obtained")
        
        # The Trivago message
        message_content = """Hi Johannes,

I've been following trivago's impressive work in transforming the travel booking experience through innovative price comparison technology. Your platform's ability to aggregate and compare prices from 400+ booking sites is truly remarkable.

As CTO at one of the world's largest hotel search platforms, you're likely focused on scaling your technology infrastructure, optimizing search algorithms, and enhancing the user experience across 55 languages and 190 countries.

At 4Runr, we specialize in helping travel technology companies like trivago optimize their operations through AI-powered automation and data analytics solutions. We've worked with similar platforms to streamline their booking processes, enhance personalization engines, and improve conversion rates.

I'd love to explore how we might help trivago further optimize your platform's performance and user engagement. Would you be open to a brief conversation about your current technology priorities and challenges in the competitive travel tech landscape?

Best regards,
4Runr Team

---
This message was generated by the 4Runr Autonomous Outreach System
Website analyzed: https://www.trivago.ca/
Target: Travel Technology Industry
Generated on: 2025-07-29"""
        
        # Send email
        print(f"\n📧 Sending email...")
        
        send_url = f"https://graph.microsoft.com/v1.0/users/{graph_config['sender_email']}/sendMail"
        
        headers = {
            'Authorization': f'Bearer {access_token}',
            'Content-Type': 'application/json'
        }
        
        email_data = {
            "message": {
                "subject": "🏨 Travel Tech Partnership - AI Solutions for trivago",
                "body": {
                    "contentType": "Text",
                    "content": message_content
                },
                "toRecipients": [
                    {
                        "emailAddress": {
                            "address": "kyanberg@outlook.com"
                        }
                    }
                ]
            }
        }
        
        send_response = requests.post(send_url, headers=headers, json=email_data)
        
        print(f"Response: {send_response.status_code}")
        
        if send_response.status_code == 202:
            print("✅ Email sent successfully!")
            print(f"\n🎉 SUCCESS!")
            print(f"The Trivago analysis message has been sent to kyanberg@outlook.com")
            print(f"This demonstrates the system's ability to:")
            print(f"   • Analyze different industries (Travel Tech vs AI Automation)")
            print(f"   • Generate industry-specific messages")
            print(f"   • Adapt tone and value propositions")
            print(f"   • Maintain professional quality across sectors")
            return True
        else:
            print(f"❌ Failed to send: {send_response.text}")
            return False
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

def main():
    """Main function."""
    print("🚀 4Runr Outreach System - Trivago Message Demo")
    print("=" * 60)
    print()
    print("This will send the Trivago-specific message to demonstrate")
    print("how the system adapts to different industries and companies.")
    print()
    
    success = send_trivago_message()
    
    if success:
        print(f"\n✅ SYSTEM DEMONSTRATION COMPLETE!")
        print(f"You now have two different messages in your inbox:")
        print(f"   1. 4Runr message (AI automation industry)")
        print(f"   2. Trivago message (travel technology industry)")
        print(f"")
        print(f"This proves the 4Runr Autonomous Outreach System can:")
        print(f"   ✅ Analyze any website")
        print(f"   ✅ Adapt to different industries")
        print(f"   ✅ Generate personalized, relevant messages")
        print(f"   ✅ Maintain high quality across all sectors")
        print(f"   ✅ Send emails automatically via Microsoft Graph")
    
    return success

if __name__ == '__main__':
    success = main()
    sys.exit(0 if success else 1)