#!/usr/bin/env python3
"""
Test script to send the generated message to kyanberg@outlook.com
"""

import sys
import smtplib
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Add the project root to Python path
sys.path.insert(0, str(Path(__file__).parent))

def send_test_message():
    """Send the test message to Kyan's email."""
    print("📧 Sending Test Message to kyanberg@outlook.com")
    print("=" * 60)
    
    try:
        # Load configuration
        sys.path.append('4runr-outreach-system')
        from shared.config import config
        
        email_config = config.get_email_config()
        
        print(f"✅ SMTP Host: {email_config['smtp_host']}")
        print(f"✅ SMTP Port: {email_config['smtp_port']}")
        print(f"✅ Username: {email_config['username']}")
        print(f"✅ Password: {'*' * len(email_config['password']) if email_config['password'] else 'NOT SET'}")
        
        if not email_config['username'] or not email_config['password'] or email_config['password'] == 'your_app_password_here':
            print("❌ SMTP credentials not properly configured!")
            print("Please update SMTP_USERNAME and SMTP_PASSWORD in 4runr-outreach-system/.env")
            return False
        
        # The personalized message we generated
        message_content = """Hi Kyan,

I've been following 4Runr's work in AI-powered business automation and I'm impressed by your approach to helping companies streamline their operations through intelligent solutions.

As a founder in the AI automation space, you're likely focused on scaling your lead generation systems and optimizing client acquisition processes. Your expertise in custom automation systems and strategic AI consulting puts you at the forefront of this rapidly evolving industry.

I'd love to explore how we might collaborate or share insights about emerging trends in AI-driven business automation. Would you be open to a brief conversation about your current priorities and the challenges you're seeing in the market?

Best regards,
4Runr Team

---
This message was generated by the 4Runr Autonomous Outreach System
Website analyzed: https://4runrtech.com/
Generated on: 2025-07-29"""
        
        # Create email message
        msg = MIMEMultipart()
        msg['From'] = email_config['username']
        msg['To'] = 'kyanberg@outlook.com'
        msg['Subject'] = '🤖 Test: AI-Generated Outreach Message - 4Runr Partnership'
        
        # Add message body
        msg.attach(MIMEText(message_content, 'plain'))
        
        print(f"\n📝 Message Preview:")
        print(f"From: {msg['From']}")
        print(f"To: {msg['To']}")
        print(f"Subject: {msg['Subject']}")
        print("-" * 60)
        print(message_content[:200] + "..." if len(message_content) > 200 else message_content)
        print("-" * 60)
        
        # Send email
        print(f"\n🚀 Sending email...")
        
        with smtplib.SMTP(email_config['smtp_host'], email_config['smtp_port']) as server:
            print(f"✅ Connected to {email_config['smtp_host']}:{email_config['smtp_port']}")
            
            server.starttls()
            print("✅ TLS encryption enabled")
            
            server.login(email_config['username'], email_config['password'])
            print("✅ Authentication successful")
            
            server.send_message(msg)
            print("✅ Message sent successfully!")
        
        print(f"\n🎉 SUCCESS!")
        print(f"The AI-generated message has been sent to kyanberg@outlook.com")
        print(f"Check your inbox for the personalized outreach message!")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to send message: {str(e)}")
        
        # Common error troubleshooting
        if "authentication failed" in str(e).lower():
            print("\n🔧 Troubleshooting:")
            print("  • Make sure you're using an App Password, not your regular password")
            print("  • For Gmail: Enable 2FA and generate an App Password")
            print("  • For Outlook: Use your Microsoft account App Password")
        elif "connection" in str(e).lower():
            print("\n🔧 Troubleshooting:")
            print("  • Check your internet connection")
            print("  • Verify SMTP_HOST and SMTP_PORT settings")
            print("  • Some networks block SMTP ports")
        
        return False


def main():
    """Main function."""
    success = send_test_message()
    return success


if __name__ == '__main__':
    success = main()
    sys.exit(0 if success else 1)