#!/usr/bin/env python3
"""
Send test email using personal Gmail account (no organizational restrictions).
"""

import sys
import smtplib
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_via_personal_gmail():
    """Send email using personal Gmail account."""
    print("📧 Sending via Personal Gmail Account")
    print("=" * 50)
    
    print("This will use a personal Gmail account to send the test message.")
    print("You'll need to provide Gmail credentials with an App Password.")
    print()
    
    # Get Gmail credentials
    gmail_address = input("Enter your personal Gmail address: ").strip()
    if not gmail_address:
        print("❌ No Gmail address provided!")
        return False
    
    print("Generate an App Password at: https://myaccount.google.com/apppasswords")
    gmail_password = input("Enter your Gmail App Password: ").strip()
    if not gmail_password:
        print("❌ No password provided!")
        return False
    
    try:
        # The personalized message
        message_content = """Hi Kyan,

I've been following 4Runr's work in AI-powered business automation and I'm impressed by your approach to helping companies streamline their operations through intelligent solutions.

As a founder in the AI automation space, you're likely focused on scaling your lead generation systems and optimizing client acquisition processes. Your expertise in custom automation systems and strategic AI consulting puts you at the forefront of this rapidly evolving industry.

I'd love to explore how we might collaborate or share insights about emerging trends in AI-driven business automation. Would you be open to a brief conversation about your current priorities and the challenges you're seeing in the market?

Best regards,
4Runr Team

---
This message was generated by the 4Runr Autonomous Outreach System
Website analyzed: https://4runrtech.com/
Generated on: 2025-07-29
Sent via: Personal Gmail (Testing)"""
        
        # Create email
        msg = MIMEMultipart()
        msg['From'] = gmail_address
        msg['To'] = 'kyanberg@outlook.com'
        msg['Subject'] = '🤖 Test: AI-Generated Outreach Message - 4Runr Partnership'
        
        msg.attach(MIMEText(message_content, 'plain'))
        
        print(f"\n📝 Sending email...")
        print(f"From: {gmail_address}")
        print(f"To: kyanberg@outlook.com")
        print(f"Subject: {msg['Subject']}")
        
        # Send via Gmail SMTP
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(gmail_address, gmail_password)
            server.send_message(msg)
        
        print("✅ Email sent successfully!")
        print(f"\n🎉 SUCCESS!")
        print(f"The AI-generated message has been sent to kyanberg@outlook.com")
        print(f"Check your inbox for the personalized outreach message!")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to send: {str(e)}")
        return False

def main():
    """Main function."""
    print("🚀 4Runr Outreach System - Personal Gmail Test")
    print("=" * 60)
    print()
    print("Since your organizational email has security restrictions,")
    print("let's test with a personal Gmail account to prove the system works.")
    print()
    
    success = send_via_personal_gmail()
    
    if success:
        print(f"\n✅ The 4Runr Autonomous Outreach System is working perfectly!")
        print(f"The only issue was the Microsoft Graph permissions.")
        print(f"Once you fix the Azure AD permissions, it will work with your business email too.")
    
    return success

if __name__ == '__main__':
    success = main()
    sys.exit(0 if success else 1)