version: '3.8'

services:
  auto-processor:
    build: .
    container_name: 4runr-auto-processor
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python auto_lead_processor.py --continuous --interval 10
    
  campaign-brain:
    build: ../4runr-brain
    container_name: 4runr-campaign-brain
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ../4runr-brain/logs:/app/logs
    ports:
      - "8080:8080"
    command: python serve_campaign_brain.py --batch-size 5
    depends_on:
      - auto-processor

networks:
  default:
    name: 4runr-network
